name= input('What is your name? ')
print('UGH, I HATE YOU '+name.upper()+'.')
color= input ('what is your favorite color? ')
print('UGH I HATE, '+color.upper()+', THERE ARE SO MANY BETTER COLORS.')
subject= input('what is your favorite subject in school? ' )
print('UGH, I HATE ' +subject.upper()+ ".")
years= input('how old are you? ' )
print('UGH, I HATE ' +years.upper()+ " year olds.")
print('I HATE EVERYTHING!')
